# Generated by Django 3.2.9 on 2021-12-07 18:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categoria', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Receita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(db_index=True, default='titulo', max_length=100, unique=True)),
                ('imagem', models.CharField(blank=True, max_length=50)),
                ('slug', models.SlugField(max_length=30)),
                ('tempo', models.CharField(blank=True, max_length=50)),
                ('rendimento', models.CharField(blank=True, max_length=50)),
                ('dificuldade', models.CharField(blank=True, max_length=50)),
                ('modo_servir', models.CharField(blank=True, max_length=50)),
                ('ingredientes', models.CharField(blank=True, max_length=500)),
                ('modo_preparo', models.CharField(blank=True, max_length=1000)),
                ('likes', models.IntegerField(default=0)),
                ('deslikes', models.IntegerField(default=0)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='receitas', to='categoria.categoria')),
            ],
            options={
                'db_table': 'receita',
                'ordering': ('titulo',),
            },
        ),
    ]
