# Generated by Django 3.2.9 on 2021-12-07 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('receitas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='receita',
            table='receitas',
        ),
    ]
