# Generated by Django 3.2.9 on 2021-12-07 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receitas', '0003_alter_receita_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receita',
            name='titulo',
            field=models.CharField(db_index=True, default='titulo', max_length=100),
        ),
    ]
