# Generated by Django 3.2.9 on 2021-12-07 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(db_index=True, default='titulo', max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100)),
                ('imagem', models.CharField(blank=True, max_length=50)),
                ('data', models.CharField(default='10/10/2020', max_length=50)),
                ('desc_mini', models.CharField(blank=True, max_length=300)),
                ('desc_full', models.CharField(blank=True, max_length=5000)),
                ('likes', models.IntegerField(default=0)),
                ('deslikes', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'noticias',
                'ordering': ('titulo',),
            },
        ),
    ]
