# Generated by Django 3.2.9 on 2021-12-07 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Loja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(db_index=True, default='titulo', max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100)),
                ('cidade', models.CharField(blank=True, max_length=50)),
                ('bairro', models.CharField(blank=True, max_length=50)),
                ('endereco', models.CharField(blank=True, max_length=100)),
                ('telefone', models.CharField(blank=True, max_length=15)),
                ('horario_sem', models.CharField(default='07h as 22h', max_length=50)),
                ('horario_fds', models.CharField(default='07h as 20h', max_length=50)),
                ('imagem', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'db_table': 'lojas',
                'ordering': ('nome',),
            },
        ),
    ]
